name: git_search
description: A project to do research on github.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  result_dart: ^1.0.3
  dio: ^4.0.6
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true
