name: git_search
description: A project to do research on github.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  result_dart: ^1.0.3
  dio: ^4.0.6
  get_it: ^7.2.0
  equatable: ^2.0.5
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  dart_code_metrics: ^4.16.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  web:
    generate: true
    image_path: "assets/image/logo.png"